package p08_petClinics;

public class Room {
    private Pet pet;
    private boolean occupied;

    public Room() {
        this.pet = null;
        this.occupied = false;
    }

    public void setPet(Pet pet) {
        this.pet = pet;
    }

    public boolean isOccupied() { // getter generated by Intellij. Not getOccupied, but isOccupied. Cool
        return this.occupied;
    }

    public void setOccupied(boolean occupied) {
        this.occupied = occupied;
    }

    @Override
    public String toString() {
        if (!this.isOccupied()) {
            return "Room empty";
        } else {
            return this.pet.toString();
        }
    }
}
